apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: locusts.boomatang.dev
spec:
  scope: Namespaced
  group: boomatang.dev
  names:
    kind: Locust
    plural: locusts
    singular: locust
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

