apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {label}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {label}
  template:
    metadata:
      labels:
        app: {label}
        controller: locust-operator
    spec:
      containers:
      - name: {name}
        image: {image}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8089
          name: ui
          protocol: TCP
        - containerPort: 5557
          name: back-channel
          protocol: TCP

