apiVersion: v1
kind: Service
metadata:
  name: {name}
  labels:
    controller: locust-operator
spec:
  selector:
    app: {label}
  ports:
    - name: http
      port: 5557
      protocol: TCP
      targetPort: 5557
    - name: ui
      port: 8089
      protocol: TCP
      targetPort: 8089
